env:
  global:
    - CC_TEST_REPORTER_ID=aa7d09060adc8243f2a6f51b6051ea2629b2f9a3c28042076f2494193bc8ad06
language: node_js
node_js:
  - "7"
  - "8"
  - "node"
git:
  submodules: false
cache:
  directories:
    - $HOME/.m2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - make

