env:
  global:
  - CC_TEST_REPORTER_ID=18c66a6738c0718369a787a4cb2e97f0bef655c5ccb747332486636fac394664
  - CODACY_PROJECT_TOKEN=61032013369f42c2883a039c33987e2c
  - SAUCE_USERNAME=bloomlabs
  - secure: PrWcsspNNByfBoQJpGc3w7BLDiUm7P+gHvTA3u6cCLgS8hFMpEDsci9JAJ02iYPYGmhNrdGI4TC6phmplvXLFfM8rIVvDCQgOrZp+wzK+03QjlzzZ2wneE6YGAg/OKTnpcKxhnZ3XnTNZjuC9LmT/ld7No8niYWXFmIP8dokJMfdHkL4fuWcfgYKwHAsqb+EA1W5EnZIM97sKq6BE5MExEHKECIQVsW3KhpEpVqKEB5MDy4/HmC7oJPSybuSZ5TaIYG6wACAnLf9gvbL5EpmeAyvs5Mk9xG5Yhx1jEF/5hiYBe/6PCLlFQSXjADNWUisluRI4DM5Uq8PiUxWwR1RqolejD/0f7JeNnX60SIpz1u4yItDO58AwMjqR9gemzc8+OJadRjoKZ8AHT2eH1XBbGk6sH3fiTXfL+XI/lWVnYrjK9OZ2r3Z536xrOgg5+kFhxn9Tz48BH/kA4RnIoOg7eOqgk+eIfiS+9I3WoccP373uWncqV/mauULRfgFAxqkLZT2GZ9y/48CPgIIy9+QZ6Agvwv9LKbXK4GR5kRyTP3CvY5tk42IgT62xVWCGkvxbALk0CxnmkW72CGYlhoryyeJuq3u2vElSz9UsxAVbeEe+jm78MUK8tjfZ6pbZ6slYO8H9DdRaFjmvc5iE13rTKUGtHk6iJ47UozLKc6g9GU=
  - secure: D2eFSLoV3F3Aa6Ew7PHZcJv6juwOhopQ85Y6UqzBY1QpWZvrQ6tOMvHHyIZcjosy04mQ0LHyuTTAITwzY66G6DQIVQqzbz0fbDDR5v0ZCgaf6IlGpIryd0dOGWPOPcIqZdAd0KJwEaqIqGm2Y5KAu8e3WnAj+QnO6MGQPqU2Zq4h1fMDkLOykKBBD2rD0fWeZmGhd1hrbM18NkmLuydNB/RPpSY38sLdVN4TTB8qnc/xj4Y8KYDZpGTafDoRe1jMcuKSn25QE2ngCFTS8AbcTAXKDR4sZCZhP2JN9kWUqwpqE63pWAYNvCtckWbbkk8h2BAuC7LnrNII+xSTPmQ5O9vK10/yubYypWPRvuvS3RfzIau/etFdEO++nSiRxhDbl4JPe1sV7Ix0YKiF7Vedt5Hlweo8uNhlUq6e2ZPzaYelv8lZnYbWART/AgjPV/I/iBhGgjPVNbUNEP3fhIxMHRmQhPV3yfZSFU5xLg+1gmqSQ6tPEbJBBxNpGosHklyP3R9qWRXkk4nWnSfFcbGBW8CvOy5K0PZ5PA2od7NR+XetxlEHxbuHfdbqK6p6tCaXABZZo6P/iYvLg4G2m8NbQOXwHYV/uLxNTSPmfPV1wuCaKdT1RUWJW00Kvp1JMY87VuxZAmG3MF3M1o07oYWCyfEHBxb5mf0RHuIBuAFMdA0=
addons:
  browserstack:
    username: samgammon2
    access_key:
      secure: jXUc+ILvweMNlYYtGcC4+WC8tZivgIq90g23bsHeLUc73q+tW5V6GoiAkawTaYmJES9r8WnUZuSvLqrnq+Z8TktGXakmRZzmpunkJXFB6wQr+PjPfvHJ4UJ/1WN5jJWMs/wuCgUGdXVrCErps4AvaR8tN1o4fWJkjtQGucKooXsE2M2yj6c+idL/CYyInCZ5W4sCH56tgLyAlqUqOd8CTNjxqujGbTt2MwJZoSYjyGZ+NCM8lfFYTxIHAe/xvotGPgl4lPeCcYYFpVedms6gR39K5uB+ifk3USJzhBH7J5CHzl7OT7CUvLyqHfYQvK9/vITB73jjAaERVDwc/lU71p1kgkL43HfaIgsAV6DXXtT1wWI+gx4VO1JBzeuHMPvR1oxMr/kPDJuZnMO+/XBdGCMrHUwGFhul6df8ZQ+8b+oyLQ43QlbJrYyKhV1Cw3xJLzgyD1+bAFFhTlFoQKLlrE+rvDvF0eeZHuJO1gnt22IJwZOFCtksmmNIAqAMsjdSqDx2NtQSCa+vhUzXlvfIREAsKScDNSte2qw7b4xdytO68Hs8+PsDz/WaxpdCIdvbHKoi+6PqRYvRq0UflFAgDHZJJw1RtWA5s8y8KeXpqFTv8jCvNWesZbB0VC/ksjd9BKgMkIC8020ZkonLfKbsH4otUWEVQASG0qRkw6VaHTg=
  sauce_connect:
    username: bloomlabs
  jwt:
    secure: noa+zpHISKyvf6CRR/CBc/npjVm5sYsvz5w2kI1vVCPjXfMBchB4um6JnAuQ3p9vdLluVURpNYJDHwCJKiZT14vdnOfNyMPqX1JHdmTacEWSQN/J2sRJsDk6mUD38SRk323wF/AtXaP+qyiTa3/i4qa6ayeTbES8QVBrhT8MFBz4yjse/0l1TmF4dFSRl45LYSrLqfZykRX7nB8ccyaHlWAF9cNCBn6xvLyDT4JfYTnH9VoDw0E+ujszxk81B0a94Xp/tQaqix+WO8T7+CcsfwLPuzrvGbSJJya32ZyRxxqO7TZjsnohOn/tb2tBmJTzWhpsQGcMtSOZy7ykWZfOdzY22G6FkoNAC60m00grRWSn2BZkDVP1181Md3l/6VkcCIpEyK2unns5d5Bfh6/1TLP0s557j0vFn0MmwY805PoGjaQGhJ4Np/f5JlRRMf1pRiE5cX/DAdzDRRI/O0PfuVmbHHGIaihUR7GdutwAHEWTwI3EIx5W6whOD7NfpZ3QwOgS7JGLM4kno1rpi0Kv/d7sfIXlwtUyFOD1R2Xu3+Ew7/8aQBR0A7t/14m0UZasn+YqmMBtPfL28WNvQMln2ETUZhvGv8uV2wavv3zp+tN7Vn+wYLYFPwsI+x9upnPhMItcnVMKtfCaRTKjgW1rIsP4ZLI9cPPlG8tP7S8c1po=
language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules/
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- curl -L https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar > ./codacy-coverage-reporter.jar
- chmod +x ./cc-test-reporter
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
- ./cc-test-reporter before-build
script:
- make
- make serve &
- karma start karma-ci.conf.js --single-run
after_script:
- cp -fv target/coverage/cobertura.xml ./cobertura.xml
- ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT --coverage-input-type cobertura --prefix /home/travis/build/Bloombox/JS/src
- java -cp codacy-coverage-reporter-2.0.2-assembly.jar com.codacy.CodacyCoverageReporter --language Javascript -r target/coverage/cobertura.xml --prefix /home/travis/build/Bloombox/JS/src
