env:
  global:
  - CC_TEST_REPORTER_ID=aa7d09060adc8243f2a6f51b6051ea2629b2f9a3c28042076f2494193bc8ad06
  - SAUCE_USERNAME=bloombox
  - secure: PrWcsspNNByfBoQJpGc3w7BLDiUm7P+gHvTA3u6cCLgS8hFMpEDsci9JAJ02iYPYGmhNrdGI4TC6phmplvXLFfM8rIVvDCQgOrZp+wzK+03QjlzzZ2wneE6YGAg/OKTnpcKxhnZ3XnTNZjuC9LmT/ld7No8niYWXFmIP8dokJMfdHkL4fuWcfgYKwHAsqb+EA1W5EnZIM97sKq6BE5MExEHKECIQVsW3KhpEpVqKEB5MDy4/HmC7oJPSybuSZ5TaIYG6wACAnLf9gvbL5EpmeAyvs5Mk9xG5Yhx1jEF/5hiYBe/6PCLlFQSXjADNWUisluRI4DM5Uq8PiUxWwR1RqolejD/0f7JeNnX60SIpz1u4yItDO58AwMjqR9gemzc8+OJadRjoKZ8AHT2eH1XBbGk6sH3fiTXfL+XI/lWVnYrjK9OZ2r3Z536xrOgg5+kFhxn9Tz48BH/kA4RnIoOg7eOqgk+eIfiS+9I3WoccP373uWncqV/mauULRfgFAxqkLZT2GZ9y/48CPgIIy9+QZ6Agvwv9LKbXK4GR5kRyTP3CvY5tk42IgT62xVWCGkvxbALk0CxnmkW72CGYlhoryyeJuq3u2vElSz9UsxAVbeEe+jm78MUK8tjfZ6pbZ6slYO8H9DdRaFjmvc5iE13rTKUGtHk6iJ47UozLKc6g9GU=
  - secure: jNy6GqulHd9T3BgjePpmJZmFUBtQ0my/lZ5Cmz269SP06S1nJwGoR8VwVzfX81E++nZi7D/ywptXJOARsmbWWtOGjqjdWqeC/a3HTDEsMo7uxmC/noeKkIDDkUzu6yXQMlyDYp5gU971SkZtysUXFWjPZ3M3pu36p08pY08l3A2cjUJLjUxhHGw6MumhxVxqhMhOonbeLf5aekQ4L9A9vTo8HdHq30FWqa7LlYGHbUpHCYe0zFntv4GVegBMDP+q3cjZwbbV86/eNs0jmSX2PAQO5MHRtIEpRuIxVJXMP0rroGgU9Od1cTXPZVFAy0bRC/GqcVklOxXfPfSkJxIVfJAjISnTfNkoPaHwwx1i6cqnuFbh+qBN9powsQBZbfBnf8jMWatrg/r/ozjn3+S5JVY2X6HDujJHM5fNRTAXFHqrDaPRHfQz/zVxwrAZDO5FVT4X5Kw/9bmsLTzZWRzUfhORK0/Yv+JxviCnELJi4XMMlypembvDmh7brFmesEY9D0Gj3/in9p7DgVDKvlzelTAdFFkn+kEccAo9Z4sHU3RCopp/72UoEgaf+xJKjruFrv+OVJWEBXr59ypjoIbW+2yv+TFCofOBncAZQE4FkSD5qqQp4bsNc0tPKBrW5wTnzwGZCLwoDbbNFNS31hB6MA1EoVcDvKQ8I6TR+eiZqNY=
addons:
  browserstack:
    username: samgammon2
    access_key:
      secure: jXUc+ILvweMNlYYtGcC4+WC8tZivgIq90g23bsHeLUc73q+tW5V6GoiAkawTaYmJES9r8WnUZuSvLqrnq+Z8TktGXakmRZzmpunkJXFB6wQr+PjPfvHJ4UJ/1WN5jJWMs/wuCgUGdXVrCErps4AvaR8tN1o4fWJkjtQGucKooXsE2M2yj6c+idL/CYyInCZ5W4sCH56tgLyAlqUqOd8CTNjxqujGbTt2MwJZoSYjyGZ+NCM8lfFYTxIHAe/xvotGPgl4lPeCcYYFpVedms6gR39K5uB+ifk3USJzhBH7J5CHzl7OT7CUvLyqHfYQvK9/vITB73jjAaERVDwc/lU71p1kgkL43HfaIgsAV6DXXtT1wWI+gx4VO1JBzeuHMPvR1oxMr/kPDJuZnMO+/XBdGCMrHUwGFhul6df8ZQ+8b+oyLQ43QlbJrYyKhV1Cw3xJLzgyD1+bAFFhTlFoQKLlrE+rvDvF0eeZHuJO1gnt22IJwZOFCtksmmNIAqAMsjdSqDx2NtQSCa+vhUzXlvfIREAsKScDNSte2qw7b4xdytO68Hs8+PsDz/WaxpdCIdvbHKoi+6PqRYvRq0UflFAgDHZJJw1RtWA5s8y8KeXpqFTv8jCvNWesZbB0VC/ksjd9BKgMkIC8020ZkonLfKbsH4otUWEVQASG0qRkw6VaHTg=
  sauce_connect:
    username: bloombox
  jwt:
    secure: noa+zpHISKyvf6CRR/CBc/npjVm5sYsvz5w2kI1vVCPjXfMBchB4um6JnAuQ3p9vdLluVURpNYJDHwCJKiZT14vdnOfNyMPqX1JHdmTacEWSQN/J2sRJsDk6mUD38SRk323wF/AtXaP+qyiTa3/i4qa6ayeTbES8QVBrhT8MFBz4yjse/0l1TmF4dFSRl45LYSrLqfZykRX7nB8ccyaHlWAF9cNCBn6xvLyDT4JfYTnH9VoDw0E+ujszxk81B0a94Xp/tQaqix+WO8T7+CcsfwLPuzrvGbSJJya32ZyRxxqO7TZjsnohOn/tb2tBmJTzWhpsQGcMtSOZy7ykWZfOdzY22G6FkoNAC60m00grRWSn2BZkDVP1181Md3l/6VkcCIpEyK2unns5d5Bfh6/1TLP0s557j0vFn0MmwY805PoGjaQGhJ4Np/f5JlRRMf1pRiE5cX/DAdzDRRI/O0PfuVmbHHGIaihUR7GdutwAHEWTwI3EIx5W6whOD7NfpZ3QwOgS7JGLM4kno1rpi0Kv/d7sfIXlwtUyFOD1R2Xu3+Ew7/8aQBR0A7t/14m0UZasn+YqmMBtPfL28WNvQMln2ETUZhvGv8uV2wavv3zp+tN7Vn+wYLYFPwsI+x9upnPhMItcnVMKtfCaRTKjgW1rIsP4ZLI9cPPlG8tP7S8c1po=
language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules/
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
script:
- make
- make serve &
- karma start karma-ci.conf.js --single-run
