#!/bin/bash

rm -fr node_modules/closure-builder/third_party/closure-library/third_party/closure/goog/svgpan
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/roundedpanel.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/serverchart.js
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/testing/performancetable.*
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/testing/benchmark.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/labs/structs/map_perf.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/json/json_perf.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/crypt/hashtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/crypt/bytestring_perf.js
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/testing/
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/module/
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/proto2/
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/net/testdata
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/labs/testing
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/style/stylescrollbartester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/storagetester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/mechanismtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/mechanismseparationtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/iterablemechanismtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/collectablestoragetester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/html/testing.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/events/eventtargettester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/mechanismtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/mechanismtestdefinition.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/storage/mechanism/mechanismsharingtester.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/promise/testsuiteadapter.js
rm -fr node_modules/closure-builder/third_party/closure-library/third_party/closure/goog/dojo
rm -fr node_modules/closure-builder/third_party/closure-library/third_party/closure/goog/caja
rm -f node_modules/closure-builder/third_party/closure-library/third_party/closure/goog/loremipsum/text/loremipsum.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/media/flashobject.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/prompt.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/popupmenu.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/imagelessmenubuttonrenderer.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/imagelessbuttonrenderer.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/gaugetheme.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/gauge.js
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/ui/emoji
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/ui/editor
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/richtextspellchecker.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/media/youtube.js
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/ui/media
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/abstractspellchecker.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/linkdialogplugin.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/linkbubble.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/emoticons.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/basictextformatter.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/abstractbubbleplugin.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/editor/plugins/abstractdialogplugin.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/plaintextspellchecker.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/soy/soy_testhelper.js
rm -fr node_modules/closure-builder/third_party/closure-library/closure/goog/result
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/tooltip.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/charpicker.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/hovercard.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/advancedtooltip.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/ui/idletimer.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/debug/tracer.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/debug/errorhandler.js
rm -f node_modules/closure-builder/third_party/closure-library/closure/goog/debug/errorreporter.js

